services:
  api:
    build: ./api
    ports:
      - "3100:3100"
    environment:
      - PYTHONPATH=/code
    volumes:
      - ./api:/code
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./web
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped

  easyauth:
    image: appsvc/middleware:1.3.2
    ports:
      - "8081:8081"
    depends_on:
      - frontend
    env_file:
      - .env
    command: [
      "/Host.ListenUrl=http://0.0.0.0:8081",
      "/Host.DestinationHostUrl=http://frontend:80",
      "/Host.UseFileLogging=true"
    ]
    restart: unless-stopped

networks:
  default:
    name: fastapi-app-network