version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "3100:3100"
    environment:
      - PYTHONPATH=/code
    volumes:
      - .:/code
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s